#!/bin/bash

# matrix
#
# Phi Luu
#
# Oregon State University
# CS_344_001_W2019 Operating Systems 1
# Program 1: Matrices

# Rounds the result of integer division to the nearest integer, away from 0.
# Source: OSU CS 344 Canvas
#
# SYNOPSIS
#   round_div DIVIDEND DIVISOR
#
# ARGUMENTS
#   DIVIDEND - the integer number to be divided up
#   DIVISOR - the integer by which the  DIVIDEND  is to be divided
#
# RETURNS
#   The rounded result to the nearest integer and away from 0.
round_div() {
  # just a fail safe to make sure there are two numbers
  if [[ "$#" -ne 2 ]] || [[ -z "$1" ]] || [[ -z "$2" ]]; then
    return 1
  fi

  # formula provided by Prof. Ben Brewster
  _RET="$((($1 + ($2 / 2) * (2 * ($1 > 0) - 1 )) / $2))"
}

# Prints the dimensions of the matrix as the number of rows, followed by a
# space, then the number of columns.
#
# SYNOPSIS
#   dims [MATRIX]
#
# ARGUMENTS
#   MATRIX - a string of EOL-separated rows, each contains an equal number of
#  tab-separated integers.
#
# RETURNS
#   None
dims() {
  # temporary file name in case of reading from stdin
  local fin="fin$$"

  # ensure there is at most 1 argument
  if [[ "$#" -gt 1 ]]; then
    echo 'Usage: ./matrix dims [MATRIX]' >&2
    exit 1
  fi
  # if using file, ensure the file is readable
  if [[ "$#" -eq 1 ]]; then
    if [[ ! -r "$1" ]]; then
      echo 'Could not read file' >&2
      exit 1
    else
      fin="$1"
    fi
  # if using stdin, cat to temporary file
  else
    cat > "${fin}"
  fi

  # read the first row of matrix as an array
  read -a header < "${fin}"

  # count the number of rows = number of newline characters
  local num_rows="$(wc -l < "${fin}")"
  # count the number of columns = number of elements in the header row
  local num_cols="${#header[@]}"

  printf "%d %d\n" "${num_rows}" "${num_cols}"
}

# Prints a matrix reflected along the main diagonal. In other words, prints the
# matrix from left to right, column first. An M-by-N matrix will be transposed
# to an N-by-M matrix.
#
# SYNOPSIS
#   transpose [MATRIX]
#
# ARGUMENTS
#   MATRIX - a string of EOL-separated rows, each contains an equal number of
#  tab-separated integers.
#
# RETURNS
#   None
transpose() {
  # temporary file name in case of reading from stdin
  local fin="fin$$"

  # ensure there is at most 1 argument
  if [[ "$#" -gt 1 ]]; then
    echo 'Usage: ./matrix transpose [MATRIX]' >&2
    exit 1
  fi
  # if using file, ensure the file is readable
  if [[ "$#" -eq 1 ]]; then
    if [[ ! -r "$1" ]]; then
      echo 'Could not read file' >&2
      exit 1
    else
      fin="$1"
    fi
  # if using stdin, use temporary file
  else
    cat > "${fin}"
  fi

  # get the number of columns
  read -a header < "${fin}"
  local num_cols="${#header[@]}"

  # # loop through the columns and transpose each of them
  # for ((i=1;i<=num_cols;i++)); do
  #   printf "%s\n" "$(cut -f "${i}" "${fin}" | column)"
  # done

  # use the dims() function to get dimensions of the matrix
  local dimensions=($(dims "${fin}"))
  local num_rows="${dimensions[0]}"
  local num_cols="${dimensions[1]}"

  # use associative arrays as pseudo-multidimensional arrays
  declare -A mat

  # read the matrix
  local i=0
  while read row; do
    # convert string to array for instant and easy access
    row=(${row})

    # read each element of the current row to matrix
    for ((j=0;j<num_cols;j++)); do
      mat["${i}","${j}"]="${row["${j}"]}"
    done

    ((i++))
  done < "${fin}"

  # transpose the matrix by reading it column-first
  for ((j=0;j<num_cols;j++)); do
    for ((i=0;i<num_rows;i++)); do
      # print with correct format
      printf "%d" "${mat["${i}","${j}"]}"
      
      if [[ "${i}" -lt "$(expr "${num_rows}" - 1)" ]]; then
        printf "\t"
      fi
    done
    
    printf "\n"
  done
}

# Takes in an M-by-N matrix and prints a 1-by-N row vector whose each element
# is the mean of the matrix's column containing that elements.
#
# SYNOPSIS
#   mean [MATRIX]
#
# ARGUMENTS
#   MATRIX - a string of EOL-separated rows, each contains an equal number of
#  tab-separated integers.
#
# RETURNS
#   None
mean() {
  # temporary file name in case of reading from stdin
  local fin="fin$$"

  # ensure there is at most 1 argument
  if [[ "$#" -gt 1 ]]; then
    echo 'Usage: ./matrix mean [MATRIX]' >&2
    exit 1
  fi
  # if using file, ensure the file is readable
  if [[ "$#" -eq 1 ]]; then
    if [[ ! -r "$1" ]]; then
      echo 'Could not read file' >&2
      exit 1
    else
      fin="$1"
    fi
  else
    cat > "${fin}"
  fi

  # use the dims() function to get dimensions of the matrix
  local dimensions=($(dims "${fin}"))
  local num_rows="${dimensions[0]}"
  local num_cols="${dimensions[1]}"

  # read each column
  for ((i=1;i<=num_cols;i++)); do
    local col="$(cut -f "${i}" "${fin}" | column)"

    # get the sum of the current column
    local sum=0
    for num in ${col}; do
      ((sum+=num))
    done

    # calculate the average and round it away from zero (0.5 rounds to 1)
    round_div "${sum}" "${num_rows}"
    local avg="${_RET}"

    # print result with correct format
    printf "%d" "${avg}"
    if [[ "${i}" -lt "${num_cols}" ]]; then
      printf "\t"
    else
      printf "\n"
    fi
  done
}

# Takes in 2 M-by-N matrices and prints a M-by-N matrix formed by adding the two
# input matrices.
#
# SYNOPSIS
#   add MATRIX_LEFT MATRIX_RIGHT
#
# ARGUMENTS
#   MATRIX_LEFT - a string of EOL-separated rows, each contains an equal number
#  of tab-separated integers.
#   MATRIX_RIGHT - a string of EOL-separated rows, each contains an equal number
#  of tab-separated integers
#
# RETURNS
#   None
add() {
  # ensure there are exactly 2 arguments
  if [[ "$#" -ne 2 ]]; then
    echo 'Usage: ./matrix add MATRIX_LEFT MATRIX_RIGHT' >&2
    exit 1
  fi
  # ensure the files are readable
  if [[ ! -r "$1" ]] || [[ ! -r "$2" ]]; then
    echo 'Could not read file(s)' >&2
    exit 1
  fi
  # ensure both matrices have the exact same dimensions
  if [[ "$(dims "$1")" != "$(dims "$2")" ]]; then
    echo 'Invalid matrix dimensions. Require two M x N matrices' >&2
    exit 1
  fi

  # use associative arrays as pseudo-multidimensional arrays
  declare -A lhs  # left-hand-side matrix
  declare -A rhs  # right-hand-side matrix

  # use the dims() function to get dimensions of the matrices
  local dimensions=($(dims "$1"))
  local num_rows="${dimensions[0]}"
  local num_cols="${dimensions[1]}"

  # read the left-hand-side matrix
  local i=0
  while read row; do
    # convert string to array for instant and easy access
    row=(${row})

    # read each element of the current row to matrix
    for ((j=0;j<num_cols;j++)); do
      lhs["${i}","${j}"]="${row["${j}"]}"
    done

    ((i++))
  done < "$1"

  # read the right-hand-side matrix
  i=0
  while read row; do
    # convert string to array for instant and easy access
    row=(${row})

    # read each element of the current row to matrix
    for ((j=0;j<num_cols;j++)); do
      rhs["${i}","${j}"]="${row["${j}"]}"
    done

    ((i++))
  done < "$2"

  # add two matrices and print results with correct format
  for ((i=0;i<num_rows;i++)); do
    for ((j=0;j<num_cols;j++)); do
      printf "%d" "$(expr "${lhs["${i}","${j}"]}" + "${rhs["${i}","${j}"]}")"

      if [[ "${j}" -lt "$(expr "${num_cols}" - 1)" ]]; then
        printf "\t"
      fi
    done
    printf "\n"
  done
}

# Takes in an M-by-N matrix and an N-by-K matrix and prints a M-by-K matrix
# formed by multiplying the two input matrices.
#
# SYNOPSIS
#   multiply MATRIX_LEFT MATRIX_RIGHT
#
# ARGUMENTS
#   MATRIX_LEFT - a string of EOL-separated rows, each contains an equal number
#  of tab-separated integers.
#   MATRIX_RIGHT - a string of EOL-separated rows, each contains an equal number
#  of tab-separated integers
#
# RETURNS
#   None
multiply() {
  # ensure there are exactly 2 arguments
  if [[ "$#" -ne 2 ]]; then
    echo 'Usage: ./matrix multiply MATRIX_LEFT MATRIX_RIGHT' >&2
    exit 1
  fi
  # ensure the files are readable
  if [[ ! -r "$1" ]] || [[ ! -r "$2" ]]; then
    echo 'Could not read file(s)' >&2
    exit 1
  fi

  # use dims() function to get the dimensions of the matrices
  local lhs_dim=($(dims "$1"))
  local rhs_dim=($(dims "$2"))
  # ensure the left-hand-side matrix has the same number of columns as the
  # number of rows in the right-hand-side matrix
  if [[ "${lhs_dim[1]}" -ne "${rhs_dim[0]}" ]]; then
    echo 'Invalid matrix dimensions. Require M x N times N x K matrices' >&2
    exit 1
  fi

  # use associative arrays as pseudo-multidimensional arrays
  declare -A lhs  # left-hand-side matrix
  declare -A rhs  # right-hand-side matrix

  # let lhs matrix has  m  rows and  n  columns
  # let rhs matrix has  n  rows and  k  columns
  local m="${lhs_dim[0]}"
  local n="${lhs_dim[1]}"
  local k="${rhs_dim[1]}"

  # read the left-hand-side matrix
  local i=0
  while read row; do
    row=(${row})  # convert string to array for instant and easy access

    # read each column of the current row to the matrix
    for ((j=0;j<n;j++)); do
      lhs["${i}","${j}"]="${row["${j}"]}"
    done

    ((i++))
  done < "$1"

  # read the right-hand-side matrix
  i=0
  while read row; do
    row=(${row})  # convert string to array for instant and easy access

    # read each column of the current row to the matrix
    for ((j=0;j<k;j++)); do
      rhs["${i}","${j}"]="${row["${j}"]}"
    done

    ((i++))
  done < "$2"

  # multiply two matrices and print results with correct format
  # loop lhs' rows third
  for ((i=0;i<m;i++)); do
    # loop rhs' columns second
    for ((j=0;j<k;j++)); do
      local dot_prod=0
      # loop lhs' columns of current row (and also rhs' rows of current column)
      for ((p=0;p<n;p++)); do
        # accumulate the dot product
        dot_prod="$(expr "${dot_prod}" + \
          "${lhs["${i}","${p}"]}" \* "${rhs["${p}","${j}"]}")"
      done

      printf "%d" "${dot_prod}"

      if [[ "${j}" -lt "$(expr "${k}" - 1)" ]]; then
        printf "\t"
      fi
    done
    printf "\n"
  done
}

# clean up temporary files on interrupt, hang-up, and termination signals
trap "rm -f fin$$" INT HUP TERM

case "$1" in
  'dims')
    dims "${@:2}"
    ;;
  'transpose')
    transpose "${@:2}"
    ;;
  'mean')
    mean "${@:2}"
    ;;
  'add')
    add "${@:2}"
    ;;
  'multiply')
    multiply "${@:2}"
    ;;
  *)
    echo 'Invalid arguments. Usage:' >&2
    echo './matrix dims [MATRIX]' >&2
    echo './matrix transpose [MATRIX]' >&2
    echo './matrix mean [MATRIX]' >&2
    echo './matrix add MATRIX_LEFT MATRIX_RIGHT' >&2
    echo './matrix multiply MATRIX_LEFT MATRIX_RIGHT' >&2
    exit 1
esac

# clean up temporary files
rm -f "fin$$"
